version: 1.0.{build}
environment:
  NugetApiKey:
    secure: GCB6CT824nBA2Mw5JiBQ10Pks9Kj7uYVypP5j+LkxKgCpFmkMmuP++rGDkJ2a9/0
build_script:
- ps: ./build.ps1 -target Package
artifacts:
- path: ./build_output/artifacts/*.nupkg
- path: ./build_output/artifacts/*.exe
- path: ./build_output/artifacts/*.pdb
deploy:
- provider: NuGet
  api_key:
    secure: GCB6CT824nBA2Mw5JiBQ10Pks9Kj7uYVypP5j+LkxKgCpFmkMmuP++rGDkJ2a9/0
  on:
    appveyor_repo_tag: true
  artifact: /*\.eCrypt.*?\.nupkg/